package com.biyoans.biyoans.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "byns_gallery")
@Getter
@Setter
public class GalleryItem {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;   // <-- Primary Key (getId() & setId() auto-generated by Lombok)

    @Column(nullable = false)
    private String imageUrl;   // Path to the uploaded file

    // optional: who uploaded, timestamps, etc.
    private String uploadedBy;
    private java.time.LocalDateTime createdAt = java.time.LocalDateTime.now();
}