# Cloud Database Configuration (Railway)
# MYSQL_PUBLIC_URL copy karke yahan paste karein, bas shuruat mein 'jdbc:' laga dena
spring.datasource.url=jdbc:mysql://root:lAqpMJeBUhGdHrXkJITFDwjxkeBQzMik@tramway.proxy.rlwy.net:16577/railway

# Agar alag-alag details dalni hain toh:
spring.datasource.username=root
spring.datasource.password=root

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Email Configuration (Mandatory for PasswordResetController)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sauravku7091@gmail.com
spring.mail.password=bggq wjrh tqbl jdhs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Ek file ka maximum size (e.g., 10MB)
spring.servlet.multipart.max-file-size=10MB
# Ek request ka total size (saari files milakar)
spring.servlet.multipart.max-request-size=10MB
cloudinary.cloud_name=dezkic1md
cloudinary.api_key=652364595789275
cloudinary.api_secret=DcRaTDH7rFvrpVZhzDt57sKw-Ho